### ISSUE TITLE
Отсутствуют .eot файлы, но указаны в font-face

### ISSUE THREAD

**Issue by zoxon** [zoxon/gulp-front#12]
```css
@font-face {
	font-family: "Noto Sans";
	src: url("../fonts/notosans.eot");
	src: url("../fonts/notosans.eot?#iefix'") format("embedded-opentype"), url("../fonts/notosans.woff") format("woff"), url("../fonts/notosans.ttf") format("truetype");
	font-weight: normal;
	font-style: normal;
}
```
